export const FETCH_PERSONS = "FETCH_PERSONS";
export const NEW_PERSON = "NEW_PERSON";
export const REMOVE_PERSON = "REMOVE_PERSON";
export const FILTER_PERSONS = "FILTER_PERSONS";
export const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export const ITEMS_LOADING = "ITEMS_LOADING";